apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ['sh', '-c', 'echo "Secret 환경 변수 확인:"; echo "USERNAME=$username (값은 보안상 숨김)"; echo "API_KEY 길이: $(echo $api_key | wc -c)"; sleep 10']
    envFrom:
    - secretRef:
        name: app-secret
  restartPolicy: Never
